#!/usr/bin/env python3
"""
Seed terminology database with common Canadian government acronyms and terms.

This script creates a SQLite database with acronyms and terminology commonly
found on government websites. The data comes from public sources and helps
improve the accuracy of simplification and translation.

PLEASE DO NOT EDIT THIS FILE UNLESS YOU ARE UPDATING THE ACRONYM OR TERM LISTS.
This file is maintained manually and should not be auto-generated.
"""

import argparse
import sqlite3
from pathlib import Path
from typing import List, Dict, Any
import json

# Common Canadian government acronyms
GOVERNMENT_ACRONYMS = [
    {
        "acronym": "CRA",
        "expansion": "Canada Revenue Agency",
        "definition": "Federal agency responsible for tax collection and benefits administration",
        "source_url": "https://www.canada.ca/en/revenue-agency.html",
        "language": "en"
    },
    {
        "acronym": "ARC",
        "expansion": "Agence du revenu du Canada",
        "definition": "Agence fédérale responsable de la perception des impôts et de l'administration des prestations",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/agence-revenu.html",
        "language": "fr"
    },
    {
        "acronym": "EI",
        "expansion": "Employment Insurance",
        "definition": "Government program providing temporary income support for unemployed workers",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/en/services/benefits/ei.html",
        "language": "en"
    },
    {
        "acronym": "AE",
        "expansion": "Assurance-emploi",
        "definition": "Programme gouvernemental offrant un soutien temporaire du revenu aux travailleurs sans emploi",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/services/prestations/ae.html",
        "language": "fr"
    },
    {
        "acronym": "CPP",
        "expansion": "Canada Pension Plan",
        "definition": "Government pension program for Canadian workers",
        "source_url": "https://www.canada.ca/en/services/benefits/publicpensions/cpp.html",
        "language": "en"
    },
    {
        "acronym": "RPC",
        "expansion": "Régime de pensions du Canada",
        "definition": "Programme de pension gouvernemental pour les travailleurs canadiens",
        "source_url": "https://www.canada.ca/fr/services/prestations/pensionspubliques/rpc.html",
        "language": "fr"
    },
    {
        "acronym": "GST",
        "expansion": "Goods and Services Tax",
        "definition": "Federal value-added tax on most goods and services",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses.html",  # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "TPS",
        "expansion": "Taxe sur les produits et services",
        "definition": "Taxe fédérale sur la valeur ajoutée sur la plupart des biens et services",
        "source_url": "https://www.canada.ca/fr/agence-revenu/services/impot/entreprises/sujets/tps-tvh-entreprises.html",  # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "HST",
        "expansion": "Harmonized Sales Tax",
        "definition": "Combined federal and provincial sales tax in participating provinces",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses.html",  # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "SIN",
        "expansion": "Social Insurance Number",
        "definition": "Nine-digit number needed to work in Canada or access government programs",
        "source_url": "https://www.canada.ca/en/employment-social-development/services/sin.html",
        "language": "en"
    },
    {
        "acronym": "NAS",
        "expansion": "Numéro d'assurance sociale",
        "definition": "Numéro à neuf chiffres nécessaire pour travailler au Canada ou accéder aux programmes gouvernementaux",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/emploi-developpement-social/services/nas.html",
        "language": "fr"
    },
    {
        "acronym": "IRCC",
        "expansion": "Immigration, Refugees and Citizenship Canada",
        "definition": "Federal department responsible for immigration and citizenship services",
        "source_url": "https://www.canada.ca/en/immigration-refugees-citizenship.html",
        "language": "en"
    },
    {
        "acronym": "ESDC",
        "expansion": "Employment and Social Development Canada",
        "definition": "Federal department responsible for employment and social programs",
        "source_url": "https://www.canada.ca/en/employment-social-development.html",
        "language": "en"
    },
    {
        "acronym": "PHAC",
        "expansion": "Public Health Agency of Canada",
        "definition": "Federal agency responsible for public health protection and promotion",
        "source_url": "https://www.canada.ca/en/public-health.html",
        "language": "en"
    },
    {
        "acronym": "ASPC",
        "expansion": "Agence de la santé publique du Canada",
        "definition": "Agence fédérale responsable de la protection et de la promotion de la santé publique",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/sante-publique.html",
        "language": "fr"
    },
    {
        "acronym": "HC",
        "expansion": "Health Canada",
        "definition": "Federal department responsible for health policy, regulation, and public health",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/en/health-canada.html",
        "language": "en"
    },
    {
        "acronym": "FSANZ",
        "expansion": "Food Standards Australia New Zealand",
        "definition": "Bi-national government agency responsible for food safety standards",
        "source_url": "https://www.foodstandards.gov.au/",
        "language": "en"
    },
    {
        "acronym": "GM",
        "expansion": "Genetically Modified",
        "definition": "Foods that have been altered using genetic engineering techniques",
        "source_url": "https://www.canada.ca/en/health-canada.html",
        "language": "en"
    },
    {
        "acronym": "OECD",
        "expansion": "Organisation for Economic Co-operation and Development",
        "definition": "International organization promoting economic development and trade",
        "source_url": "https://www.oecd.org/",
        "language": "en"
    },
    {
        "acronym": "OCDE",
        "expansion": "Organisation de coopération et de développement économiques",
        "definition": "Organisation internationale promouvant le développement économique et le commerce",  # pylint: disable=line-too-long
        "source_url": "https://www.oecd.org/fr/",
        "language": "fr"
    },
    {
        "acronym": "CDSA",
        "expansion": "Controlled Drugs and Substances Act",
        "definition": "Federal legislation controlling drugs and substances in Canada",
        "source_url": "https://laws-lois.justice.gc.ca/eng/acts/c-38.8/",
        "language": "en"
    },
    {
        "acronym": "NCR",
        "expansion": "Narcotic Control Regulations",
        "definition": "Federal regulations controlling narcotic substances",
        "source_url": "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.%2C_c._1041/",
        "language": "en"
    },
    {
        "acronym": "FDR",
        "expansion": "Food and Drug Regulations",
        "definition": "Federal regulations controlling food and drug safety in Canada",
        "source_url": "https://laws-lois.justice.gc.ca/eng/regulations/C.R.C.%2C_c._870/",
        "language": "en"
    },
    {
        "acronym": "PDF",
        "expansion": "Portable Document Format",
        "definition": "File format for presenting documents consistently across platforms",
        "source_url": "https://www.adobe.com/acrobat/about-adobe-pdf.html",
        "language": "en"
    },
    {
        "acronym": "WHO",
        "expansion": "World Health Organization",
        "definition": "United Nations agency for international health matters",
        "source_url": "https://www.who.int/",
        "language": "en"
    },
    {
        "acronym": "OMS",
        "expansion": "Organisation mondiale de la santé",
        "definition": "Agence des Nations Unies pour les questions de santé internationale",
        "source_url": "https://www.who.int/fr",
        "language": "fr"
    },
    {
        "acronym": "FAQ",
        "expansion": "Frequently Asked Questions",
        "definition": "Common questions and answers about a topic",
        "source_url": "",
        "language": "en"
    },
    {
        "acronym": "FAO",
        "expansion": "Food and Agriculture Organization",
        "definition": "United Nations agency for food and agriculture",
        "source_url": "https://www.fao.org/",
        "language": "en"
    },
    {
        "acronym": "UNICEF",
        "expansion": "United Nations International Children's Emergency Fund",
        "definition": "United Nations agency providing humanitarian aid to children worldwide",  # pylint: disable=line-too-long
        "source_url": "https://www.unicef.org/",
        "language": "en"
    },
    {
        "acronym": "NATO",
        "expansion": "North Atlantic Treaty Organization",
        "definition": "Intergovernmental military alliance between North American and European countries",  # pylint: disable=line-too-long
        "source_url": "https://www.nato.int/",
        "language": "en"
    },
    {
        "acronym": "OTAN",
        "expansion": "Organisation du traité de l'Atlantique nord",
        "definition": "Alliance militaire intergouvernementale entre les pays d'Amérique du Nord et d'Europe",  # pylint: disable=line-too-long
        "source_url": "https://www.nato.int/cps/fr/natohq/index.htm",
        "language": "fr"
    },
    {
        "acronym": "UE",
        "expansion": "Union européenne",
        "definition": "Union politique et économique de 27 États membres européens",
        "source_url": "https://europa.eu/",
        "language": "fr"
    },
    {
        "acronym": "EU",
        "expansion": "European Union",
        "definition": "Political and economic union of 27 European member states",
        "source_url": "https://europa.eu/",
        "language": "en"
    },
    {
        "acronym": "IMF",
        "expansion": "International Monetary Fund",
        "definition": "International organization promoting global monetary cooperation and financial stability",  # pylint: disable=line-too-long
        "source_url": "https://www.imf.org/",
        "language": "en"
    },
    {
        "acronym": "FMI",
        "expansion": "Fonds monétaire international",
        "definition": "Organisation internationale promouvant la coopération monétaire mondiale et la stabilité financière",  # pylint: disable=line-too-long
        "source_url": "https://www.imf.org/fr/Home",
        "language": "fr"
    },
    {
        "acronym": "GDP",
        "expansion": "Gross Domestic Product",
        "definition": "Monetary measure of the market value of all final goods and services produced in a country",  # pylint: disable=line-too-long
        "source_url": "https://www.imf.org/external/pubs/ft/fandd/basics/gdp.htm",
        "language": "en"
    },
    {
        "acronym": "PIB",
        "expansion": "Produit intérieur brut",
        "definition": "Mesure monétaire de la valeur marchande de tous les biens et services finaux produits dans un pays",  # pylint: disable=line-too-long
        "source_url": "https://www.imf.org/external/pubs/ft/fandd/basics/gdp.htm",
        "language": "fr"
    },
    {
        "acronym": "OAS",
        "expansion": "Old Age Security",
        "definition": "Government pension program for seniors in Canada",
        "source_url": "https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "OAS",
        "expansion": "Sécurité de la vieillesse",
        "definition": "Programme de pension gouvernemental pour les personnes âgées au Canada",
        "source_url": "https://www.canada.ca/fr/services/prestations/pensions-publiques/rrq/securite-vieillesse.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "NSLSC",
        "expansion": "National Student Loans Service Centre",
        "definition": "Canadian government service that manages student loans",
        "source_url": "https://www.canada.ca/en/services/benefits/education/student-loans.html",
        "language": "en"
    },
    {
        "acronym": "CDCP",
        "expansion": "Canada Disability Savings Program",
        "definition": "Federal program to help Canadians with disabilities save for the future",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/employers-guide/benefits/registered-disability-savings-plan.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "CDB",
        "expansion": "Canada Disability Benefit",
        "definition": "Proposed federal benefit to support Canadians with disabilities",
        "source_url": "https://www.canada.ca/en/employment-social-development/programs/disability-benefit.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "PDC",
        "expansion": "Prestation canadienne pour les personnes handicapées",
        "definition": "Prestation fédérale proposée pour soutenir les Canadiens handicapés",
        "source_url": "https://www.canada.ca/fr/emploi-developpement-social/programmes/prestation-handicapes.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "AIPD",
        "expansion": "Assurance-invalidité du Canada",
        "definition": "Programme fédéral d'assurance pour les travailleurs canadiens incapables de travailler en raison d'une invalidité",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/services/prestations/ae/assurance-invalidite.html",
        "language": "fr"
    },
    {
        "acronym": "CID",
        "expansion": "Canada Disability Insurance",
        "definition": "Federal insurance program for Canadian workers unable to work due to disability",  # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/en/services/benefits/ei/ei-regular-benefit/ei-disability-benefit.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "CBC",
        "expansion": "Canadian Broadcasting Corporation",
        "definition": "Canada's national public broadcaster",
        "source_url": "https://www.cbc.ca/",
        "language": "en"
    },
    {
        "acronym": "SRC",
        "expansion": "Société Radio-Canada",
        "definition": "Radiodiffuseur public national du Canada",
        "source_url": "https://www.radio-canada.ca/",
        "language": "fr"
    },
    {
        "acronym": "RCMP",
        "expansion": "Royal Canadian Mounted Police",
        "definition": "Canada's federal and national law enforcement agency",
        "source_url": "https://www.rcmp-grc.gc.ca/",
        "language": "en"
    },
    {
        "acronym": "GRC",
        "expansion": "Gendarmerie royale du Canada",
        "definition": "Agence fédérale et nationale d'application de la loi du Canada",
        "source_url": "https://www.rcmp-grc.gc.ca/fr",
        "language": "fr"
    },
    {
        "acronym": "CPC",
        "expansion": "Conservative Party of Canada",
        "definition": "Major political party in Canada",
        "source_url": "https://www.conservative.ca/",
        "language": "en"
    },
    {
        "acronym": "PCC",
        "expansion": "Parti conservateur du Canada",
        "definition": "Parti politique majeur au Canada",
        "source_url": "https://www.conservative.ca/fr",
        "language": "fr"
    },
    {
        "acronym": "LPC",
        "expansion": "Liberal Party of Canada",
        "definition": "Major political party in Canada",
        "source_url": "https://www.liberal.ca/",
        "language": "en"
    },
    {
        "acronym": "PLC",
        "expansion": "Parti libéral du Canada",
        "definition": "Parti politique majeur au Canada",
        "source_url": "https://www.liberal.ca/",
        "language": "fr"
    },
    {
        "acronym": "NDP",
        "expansion": "New Democratic Party",
        "definition": "Major political party in Canada",
        "source_url": "https://www.ndp.ca/",
        "language": "en"
    },
    {
        "acronym": "NPD",
        "expansion": "Nouveau Parti démocratique",
        "definition": "Parti politique majeur au Canada",
        "source_url": "https://www.ndp.ca/fr",
        "language": "fr"
    },
    {
        "acronym": "CERB",
        "expansion": "Canada Emergency Response Benefit",
        "definition": "Temporary income support program for workers affected by COVID-19",
        "source_url": "https://www.canada.ca/en/services/benefits/ei/cerb-application.html",
        "language": "en"
    },
    {
        "acronym": "PCU",
        "expansion": "Prestation canadienne d'urgence",
        "definition": "Programme temporaire de soutien du revenu pour les travailleurs touchés par la COVID-19", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/services/prestations/ae/pcusc-application.html",
        "language": "fr"
    },
    {
        "acronym": "CCB",
        "expansion": "Canada Child Benefit",
        "definition": "Tax-free monthly payment to help with the cost of raising children",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "ACE",
        "expansion": "Allocation canadienne pour enfants",
        "definition": "Paiement mensuel libre d'impôt pour aider avec les coûts d'élever des enfants", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/agence-revenu/services/prestations-enfants-familles/allocation-canadienne-enfants-apercu.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "GIS",
        "expansion": "Guaranteed Income Supplement",
        "definition": "Monthly benefit for low-income Old Age Security recipients",
        "source_url": "https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security/guaranteed-income-supplement.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "SRG",
        "expansion": "Supplément de revenu garanti",
        "definition": "Prestation mensuelle pour les bénéficiaires de la Sécurité de la vieillesse à faible revenu", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/services/prestations/pensionspubliques/rrq/securite-vieillesse/supplement-revenu-garanti.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "TFSA",
        "expansion": "Tax-Free Savings Account",
        "definition": "Registered account that allows tax-free growth of investments",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "CELI",
        "expansion": "Compte d'épargne libre d'impôt",
        "definition": "Compte enregistré qui permet la croissance libre d'impôt des placements",
        "source_url": "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/compte-epargne-libre-impot.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "RRSP",
        "expansion": "Registered Retirement Savings Plan",
        "definition": "Tax-sheltered retirement savings account",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/rrsps-related-plans.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "REER",
        "expansion": "Régime enregistré d'épargne-retraite",
        "definition": "Compte d'épargne-retraite à l'abri de l'impôt",
        "source_url": "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/reer-regimes-connexes.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "RESP",
        "expansion": "Registered Education Savings Plan",
        "definition": "Education savings account with government grants",
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/registered-education-savings-plans-resps.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "REEE",
        "expansion": "Régime enregistré d'épargne-études",
        "definition": "Compte d'épargne-études avec subventions gouvernementales",
        "source_url": "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/regimes-enregistres-epargne-etudes-reee.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "CESG",
        "expansion": "Canada Education Savings Grant",
        "definition": "Government contribution to Registered Education Savings Plans",
        "source_url": "https://www.canada.ca/en/employment-social-development/services/learning-bond/education-savings.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "SCEE",
        "expansion": "Subvention canadienne pour l'épargne-études",
        "definition": "Contribution gouvernementale aux Régimes enregistrés d'épargne-études",
        "source_url": "https://www.canada.ca/fr/emploi-developpement-social/services/bon-etudes/epargne-etudes.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "WITB",
        "expansion": "Working Income Tax Benefit",
        "definition": "Refundable tax credit for low-income working individuals and families",
        "source_url": "https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/federal-government-budgets/budget-2018-equality-growth-strong-middle-class/canada-workers-benefit.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "PFRT",
        "expansion": "Prestation fiscale pour le revenu de travail",
        "definition": "Crédit d'impôt remboursable pour les particuliers et familles à faible revenu qui travaillent", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/agence-revenu/programmes/a-propos-agence-revenu-canada-arc/budgets-gouvernement-federal/budget-2018-egalite-croissance-classe-moyenne-forte/allocation-canadienne-travailleurs.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "CWB",
        "expansion": "Canada Workers Benefit",
        "definition": "Refundable tax credit for low and modest-income working individuals and families", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/federal-government-budgets/budget-2018-equality-growth-strong-middle-class/canada-workers-benefit.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "ACT",
        "expansion": "Allocation canadienne pour les travailleurs",
        "definition": "Crédit d'impôt remboursable pour les particuliers et familles à revenu faible et modeste qui travaillent", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/agence-revenu/programmes/a-propos-agence-revenu-canada-arc/budgets-gouvernement-federal/budget-2018-egalite-croissance-classe-moyenne-forte/allocation-canadienne-travailleurs.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "RDSP",
        "expansion": "Registered Disability Savings Plan",
        "definition": "Long-term savings plan to help Canadians with disabilities save for the future", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/registered-disability-savings-plan-rdsp.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "REEI",
        "expansion": "Régime enregistré d'épargne-invalidité",
        "definition": "Plan d'épargne à long terme pour aider les Canadiens handicapés à épargner pour l'avenir", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/agence-revenu/services/impot/particuliers/sujets/regime-enregistre-epargne-invalidite-reei.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "CDSG",
        "expansion": "Canada Disability Savings Grant",
        "definition": "Government grant for Registered Disability Savings Plans",
        "source_url": "https://www.canada.ca/en/employment-social-development/programs/disability/savings/grant.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "SCEI",
        "expansion": "Subvention canadienne pour l'épargne-invalidité",
        "definition": "Subvention gouvernementale pour les Régimes enregistrés d'épargne-invalidité", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/emploi-developpement-social/programmes/invalidite/epargne/subvention.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "CDSB",
        "expansion": "Canada Disability Savings Bond",
        "definition": "Government bond for Registered Disability Savings Plans",
        "source_url": "https://www.canada.ca/en/employment-social-development/programs/disability/savings/bond.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "BCEI",
        "expansion": "Bon canadien pour l'épargne-invalidité",
        "definition": "Bon gouvernemental pour les Régimes enregistrés d'épargne-invalidité",
        "source_url": "https://www.canada.ca/fr/emploi-developpement-social/programmes/invalidite/epargne/bon.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "CLC",
        "expansion": "Canada Labour Code",
        "definition": "Federal legislation governing employment standards and labor relations",
        "source_url": "https://www.canada.ca/en/employment-social-development/programs/laws-regulations/labour/interpretations-policies/canada-labour-code.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "CTC",
        "expansion": "Code du travail du Canada",
        "definition": "Législation fédérale régissant les normes d'emploi et les relations de travail", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/emploi-developpement-social/programmes/lois-reglements/travail/interpretations-politiques/code-travail-canada.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "PIPEDA",
        "expansion": "Personal Information Protection and Electronic Documents Act",
        "definition": "Federal privacy law for private sector organizations",
        "source_url": "https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "LPRPDE",
        "expansion": "Loi sur la protection des renseignements personnels et les documents électroniques", # pylint: disable=line-too-long
        "definition": "Loi fédérale sur la vie privée pour les organisations du secteur privé",
        "source_url": "https://www.priv.gc.ca/fr/sujets-lies-a-la-vie-privee/lois-sur-la-vie-privee-au-canada/la-loi-sur-la-protection-des-renseignements-personnels-et-les-documents-electroniques-lprpde/", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "ATIA",
        "expansion": "Access to Information Act",
        "definition": "Federal law providing right of access to information in government institutions", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/en/treasury-board-secretariat/services/access-information-privacy/access-information.html", # pylint: disable=line-too-long
        "language": "en"
    },
    {
        "acronym": "LAI",
        "expansion": "Loi sur l'accès à l'information",
        "definition": "Loi fédérale accordant le droit d'accès à l'information dans les institutions gouvernementales", # pylint: disable=line-too-long
        "source_url": "https://www.canada.ca/fr/secretariat-conseil-tresor/services/acces-information-protection-renseignements-personnels/acces-information.html", # pylint: disable=line-too-long
        "language": "fr"
    },
    {
        "acronym": "COVID",
        "expansion": "Coronavirus Disease 2019",
        "definition": "Infectious disease caused by the SARS-CoV-2 virus",
        "source_url": "https://www.who.int/health-topics/coronavirus#tab=tab_1",
        "language": "en"
    },
    {
        "acronym": "MSCA",
        "expansion": "My Service Canada Account",
        "definition": "Online portal for accessing government services and benefits",
        "source_url": "https://www.canada.ca/en/employment-social-development/services/my-service-canada-account.html", # pylint: disable=line-too-long
        "language": "en"
    }
]

# Common government terms for translation consistency
GOVERNMENT_TERMS = [
    {
        "term_en": "Canada Revenue Agency",
        "term_fr": "Agence du revenu du Canada",
        "definition_en": "Federal agency responsible for tax collection",
        "definition_fr": "Agence fédérale responsable de la perception des impôts",
        "category": "organization",
        "official": True
    },
    {
        "term_en": "Employment Insurance",
        "term_fr": "Assurance-emploi",
        "definition_en": "Temporary income support for unemployed workers",
        "definition_fr": "Soutien temporaire du revenu pour les travailleurs sans emploi",
        "category": "program",
        "official": True
    },
    {
        "term_en": "Canada Pension Plan",
        "term_fr": "Régime de pensions du Canada",
        "definition_en": "Government pension program",
        "definition_fr": "Programme de pension gouvernemental",
        "category": "program",
        "official": True
    },
    {
        "term_en": "Social Insurance Number",
        "term_fr": "Numéro d'assurance sociale",
        "definition_en": "Nine-digit identification number",
        "definition_fr": "Numéro d'identification à neuf chiffres",
        "category": "document",
        "official": True
    },
    {
        "term_en": "Goods and Services Tax",
        "term_fr": "Taxe sur les produits et services",
        "definition_en": "Federal value-added tax",
        "definition_fr": "Taxe fédérale sur la valeur ajoutée",
        "category": "tax",
        "official": True
    },
    {
        "term_en": "Harmonized Sales Tax",
        "term_fr": "Taxe de vente harmonisée",
        "definition_en": "Combined federal and provincial sales tax",
        "definition_fr": "Taxe de vente fédérale et provinciale combinée",
        "category": "tax",
        "official": True
    },
    {
        "term_en": "Public Health Agency of Canada",
        "term_fr": "Agence de la santé publique du Canada",
        "definition_en": "Federal agency for public health",
        "definition_fr": "Agence fédérale de la santé publique",
        "category": "organization",
        "official": True
    },
    {
        "term_en": "Health Canada",
        "term_fr": "Santé Canada",
        "definition_en": "Federal department for health policy",
        "definition_fr": "Ministère fédéral de la politique de santé",
        "category": "organization",
        "official": True
    },
    {
        "term_en": "benefit",
        "term_fr": "prestation",
        "definition_en": "Government financial assistance payment",
        "definition_fr": "Paiement d'aide financière gouvernementale",
        "category": "general",
        "official": True
    },
    {
        "term_en": "application",
        "term_fr": "demande",
        "definition_en": "Request for government services or benefits",
        "definition_fr": "Demande de services ou prestations gouvernementaux",
        "category": "process",
        "official": True
    },
    {
        "term_en": "eligibility",
        "term_fr": "admissibilité",
        "definition_en": "Meeting the requirements for a program or service",
        "definition_fr": "Satisfaire aux exigences d'un programme ou service",
        "category": "process",
        "official": True
    },
    {
        "term_en": "tax return",
        "term_fr": "déclaration de revenus",
        "definition_en": "Annual report of income and taxes",
        "definition_fr": "Rapport annuel des revenus et impôts",
        "category": "document",
        "official": True
    },
    {
        "term_en": "refund",
        "term_fr": "remboursement",
        "definition_en": "Money returned by the government",
        "definition_fr": "Argent retourné par le gouvernement",
        "category": "financial",
        "official": True
    },
    {
        "term_en": "assessment",
        "term_fr": "cotisation",
        "definition_en": "Government evaluation of taxes owed or benefits",
        "definition_fr": "Évaluation gouvernementale des impôts dus ou prestations",
        "category": "process",
        "official": True
    },
    {
        "term_en": "notice",
        "term_fr": "avis",
        "definition_en": "Official government communication",
        "definition_fr": "Communication officielle du gouvernement",
        "category": "document",
        "official": True
    },
    {
        "term_en": "direct deposit",
        "term_fr": "dépôt direct",
        "definition_en": "Electronic transfer of payments to bank account",
        "definition_fr": "Transfert électronique de paiements au compte bancaire",
        "category": "process",
        "official": True
    },
    {
        "term_en": "service",
        "term_fr": "service",
        "definition_en": "Government assistance or program offered to citizens",
        "definition_fr": "Aide ou programme gouvernemental offert aux citoyens",
        "category": "general",
        "official": True
    },
    {
        "term_en": "immigration",
        "term_fr": "immigration",
        "definition_en": "Process of moving to Canada to live permanently",
        "definition_fr": "Processus de déménagement au Canada pour y vivre en permanence",
        "category": "process",
        "official": True
    },
    {
        "term_en": "citizenship",
        "term_fr": "citoyenneté",
        "definition_en": "Legal status as a member of Canada",
        "definition_fr": "Statut légal de membre du Canada",
        "category": "status",
        "official": True
    },
    {
        "term_en": "passport",
        "term_fr": "passeport",
        "definition_en": "Official travel document issued by the government",
        "definition_fr": "Document de voyage officiel émis par le gouvernement",
        "category": "document",
        "official": True
    },
    {
        "term_en": "permit",
        "term_fr": "permis",
        "definition_en": "Official authorization for specific activities",
        "definition_fr": "Autorisation officielle pour des activités spécifiques",
        "category": "document",
        "official": True
    },
    {
        "term_en": "registration",
        "term_fr": "inscription",
        "definition_en": "Process of signing up for government services",
        "definition_fr": "Processus d'inscription aux services gouvernementaux",
        "category": "process",
        "official": True
    },
    {
        "term_en": "deadline",
        "term_fr": "date limite",
        "definition_en": "Final date for completing a requirement",
        "definition_fr": "Date finale pour compléter une exigence",
        "category": "time",
        "official": True
    },
]


def create_database(db_path: Path) -> None:
    """Create the terminology database with initial schema."""
    print(f"Creating database at {db_path}")

    # Ensure directory exists
    db_path.parent.mkdir(parents=True, exist_ok=True)

    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()

        # Create acronyms table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS acronyms (
                id INTEGER PRIMARY KEY,
                acronym TEXT UNIQUE,
                expansion TEXT,
                definition TEXT,
                source_url TEXT,
                language TEXT DEFAULT 'en',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Create terms table for translation consistency
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS terms (
                id INTEGER PRIMARY KEY,
                term_en TEXT,
                term_fr TEXT,
                definition_en TEXT,
                definition_fr TEXT,
                category TEXT,
                official BOOLEAN DEFAULT FALSE,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Create indexes for faster lookups
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_acronym ON acronyms(acronym)")
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_term_en ON terms(term_en)")
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_term_fr ON terms(term_fr)")
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_language ON acronyms(language)")

        conn.commit()
        print("✅ Database schema created")


def seed_acronyms(db_path: Path, acronyms: List[Dict[str, Any]]) -> None:
    """Seed the database with acronym data."""
    print(f"Seeding {len(acronyms)} acronyms...")

    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()

        for acronym_data in acronyms:
            try:
                cursor.execute("""
                    INSERT OR REPLACE INTO acronyms 
                    (acronym, expansion, definition, source_url, language)
                    VALUES (?, ?, ?, ?, ?)
                """, (
                    acronym_data["acronym"],
                    acronym_data["expansion"],
                    acronym_data["definition"],
                    acronym_data["source_url"],
                    acronym_data["language"]
                ))
            except sqlite3.Error as e:
                print(
                    f"❌ Failed to insert acronym {acronym_data['acronym']}: {e}")

        conn.commit()
        print("✅ Acronyms seeded")


def seed_terms(db_path: Path, terms: List[Dict[str, Any]]) -> None:
    """Seed the database with translation term data."""
    print(f"Seeding {len(terms)} terms...")

    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()

        for term_data in terms:
            try:
                cursor.execute("""
                    INSERT OR REPLACE INTO terms 
                    (term_en, term_fr, definition_en, definition_fr, category, official)
                    VALUES (?, ?, ?, ?, ?, ?)
                """, (
                    term_data["term_en"],
                    term_data["term_fr"],
                    term_data["definition_en"],
                    term_data["definition_fr"],
                    term_data["category"],
                    term_data["official"]
                ))
            except sqlite3.Error as e:
                print(f"❌ Failed to insert term {term_data['term_en']}: {e}")

        conn.commit()
        print("✅ Terms seeded")


def load_custom_data(file_path: Path) -> List[Dict[str, Any]]:
    """Load custom acronym/term data from JSON file."""
    if not file_path.exists():
        return []

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            print(f"📄 Loaded {len(data)} items from {file_path}")
            return data
    except (json.JSONDecodeError, FileNotFoundError) as e:
        print(f"❌ Failed to load {file_path}: {e}")
        return []


def print_stats(db_path: Path) -> None:
    """Print database statistics."""
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()

        cursor.execute("SELECT COUNT(*) FROM acronyms")
        acronym_count = cursor.fetchone()[0]

        cursor.execute("SELECT COUNT(*) FROM terms")
        term_count = cursor.fetchone()[0]

        cursor.execute("SELECT COUNT(*) FROM acronyms WHERE language = 'en'")
        en_acronym_count = cursor.fetchone()[0]

        cursor.execute("SELECT COUNT(*) FROM acronyms WHERE language = 'fr'")
        fr_acronym_count = cursor.fetchone()[0]

        print("\n📊 Database Statistics:")
        print(f"   Total acronyms: {acronym_count}")
        print(f"   English acronyms: {en_acronym_count}")
        print(f"   French acronyms: {fr_acronym_count}")
        print(f"   Translation terms: {term_count}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Seed MapleClear terminology database")
    parser.add_argument(
        "--out",
        type=Path,
        default="data/terms.sqlite",
        help="Output database path (default: data/terms.sqlite)"
    )
    parser.add_argument(
        "--custom-acronyms",
        type=Path,
        help="Path to custom acronyms JSON file"
    )
    parser.add_argument(
        "--custom-terms",
        type=Path,
        help="Path to custom terms JSON file"
    )
    parser.add_argument(
        "--stats-only",
        action="store_true",
        help="Only print database statistics"
    )

    args = parser.parse_args()

    if args.stats_only:
        if args.out.exists():
            print_stats(args.out)
        else:
            print(f"❌ Database not found: {args.out}")
        return

    print("🍁 MapleClear Terminology Database Seeder")
    print("=" * 50)

    create_database(args.out)

    all_acronyms = GOVERNMENT_ACRONYMS.copy()
    all_terms = GOVERNMENT_TERMS.copy()

    if args.custom_acronyms:
        custom_acronyms = load_custom_data(args.custom_acronyms)
        all_acronyms.extend(custom_acronyms)

    if args.custom_terms:
        custom_terms = load_custom_data(args.custom_terms)
        all_terms.extend(custom_terms)

    seed_acronyms(args.out, all_acronyms)
    seed_terms(args.out, all_terms)

    print_stats(args.out)

    print(f"\n✅ Database seeded successfully: {args.out}")
    print("Use --stats-only to view statistics anytime")


if __name__ == "__main__":
    main()
